services:
  - type: web
    name: osg-myg-portal
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --timeout 120 --workers 1 --threads 8 app:app
    plan: free
    region: singapore # Optional, but good for latency if user is in India (closest usually) or Frankfurt. Let's omit strict region or default.
